esphome:
  name: final-speaker-test

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
  # ПРЯМАЯ ИНИЦИАЛИЗАЦИЯ ПАМЯТИ ДЛЯ N16R8
  board_build.arduino.memory_type: opi_opi
  board_build.flash_mode: opi
  
api:
ota:
  platform: esphome

logger:
  level: DEBUG

wifi:
  networks:
    - ssid: "OpenWrt-2П"
      password: "35353535"
      bssid: 50:4F:3B:3F:A6:A2
  fast_connect: true
