esphome:
  name: esp32-s3-home

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino # Оставляем ардуино, раз оно скомпилировалось

# Веб-сервер, чтобы проверить работу через браузер по IP
web_server:
  port: 80

wifi:
  ssid: "OpenWrt-ASCII"
  password: "35353535"
  fast_connect: true      # Критично для OpenWrt
  power_save_mode: none   # Чтобы Wi-Fi не "засыпал" во время звука

api:
  reboot_timeout: 0s      # Чтобы плата не уходила в ребут, если нет связи с HA

ota:
  platform: esphome

logger:
  level: DEBUG

i2s_audio:
  - id: i2s_bus
    i2s_lrclk_pin: GPIO6
    i2s_bclk_pin: GPIO5

media_player:
  - platform: i2s_audio
    name: "Smart Speaker Media Player"
    id: my_media_player
    i2s_audio_id: i2s_bus
    i2s_dout_pin: GPIO7
    dac_type: external
    mode: mono

microphone:
  - platform: i2s_audio
    id: my_mic
    i2s_audio_id: i2s_bus
    i2s_din_pin: GPIO4
    adc_type: external
    pdm: false

voice_assistant:
  id: va
  microphone: my_mic
  media_player: my_media_player

binary_sensor:
  - platform: gpio
    name: "Action Button"
    pin:
      number: GPIO15
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      - voice_assistant.start
