esphome:
  name: final-speaker-test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino # Самый простой вариант для S3

api:
ota:
  platform: esphome

logger:
  level: DEBUG

wifi:
  networks:
    - ssid: "OpenWrt-2П"
      password: "35353535"
      bssid: 50:4F:3B:3F:A6:A2
  fast_connect: true
  power_save_mode: none
