name: Build ESPHome Manual

on:
  workflow_dispatch:
  push:
    branches: [ "основной" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Build Firmware
        run: esphome compile speaker.yaml

      # ЭТА ЧАСТЬ САМА НАЙДЕТ ФАЙЛ И ВЫЛОЖИТ ЕГО
      - name: Find and Copy Firmware
        run: |
          find .esphome/build/ -name "firmware.bin" -exec cp {} ./ready_to_flash.bin \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-esp32-firmware
          path: ready_to_flash.bin
